site_name: Cartografia Social

repo_name: "2021-2-Cartografia-social-Docs"
repo_url: "https://github.com/fga-eps-mds/2021-2-Cartografia-social-Doc"

theme: 
  name: material
  language: pt
  logo: img/logo.jpg
  favicon: img/logo.jpg

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Organização:
    - Metodologia utilizada: metodologia.md
    - Heatmap: heatmap.md
    - Quadro de conhecimento: conhecimentos.md
    - EAP: eap.md
    # - Gráfico de Gantt: index.md
  - Produto: 
    - Visão do Produto: leanInception.md
    - Plano de Custos: custos.md
    - Plano de Gerenciamento de Riscos: riscos.md
    - Documento de arquitetura: arquitetura.md
    - Validação de US: validacao.md
  - Pipelines:
    - Pipelines Devops: pipelines.md
