site_name: Cartografia Social
theme: 
  name: material

nav:
  - Home: index.md
  - Organização:
    - EAP: eap.md
    - Heatmap: heatmap.md
    - Quadro de conhecimento: conhecimentos.md
  - Produto: 
    - Lean Inception: leanInception.md
    - Backlog do Produto: backlog.md